In [1]:
import pandas as pd

df = pd.read_parquet(
    "../data/processed/summaries_only.parquet"
)

print(df.shape)

df.head()

(26688, 3)

,case_name,year,legal_summary
0,A_K_Gopalan_vs_The_State_Of_Madras_Union_Of_In...,1950,The petitioner who was detained under the Pre...
1,A_M_Mair_Co_vs_Gordhandass_Sagarmull_on_30_Nov...,1950,A.M. Mair & Co vs Gordhandass Sagarmull on 30...
2,Abdulla_Ahmed_vs_Animendra_Kissen_Mitter_on_14...,1950,"The appellant, an estate broker, was employed..."
3,Arjuna_Lal_Misra_vs_The_State_on_30_November_1...,1950,"Fazl Ali, J. 1. I do not wish to express diss..."
4,Ashutosh_Lahiry_vs_The_State_Of_Delhi_And_Anr_...,1950,"""You came to Delhi on March 27, 1950 and held..."

In [2]:
print(df.columns)

Index(['case_name', 'year', 'legal_summary'], dtype='str')

In [3]:
sample_df = df.sample(
    100,
    random_state=42
)

sample_df = sample_df.reset_index(drop=True)

sample_df.head()

,case_name,year,legal_summary
0,Rattan_Singh_Ran_Singh_And_Anr_vs_State_Of_Pun...,1988,"dated 19th March, 1984. These three appellant..."
1,Punjab_National_Bank_vs_R_L_Vaid_And_Ors_on_20...,2004,: 20/08/2004 BENCH: ARIJIT PASAYAT & C.K. THAK...
2,Magiti_Sasamal_vs_Pandab_Bissoi_on_20_Septembe...,1961,The appellant filed in the Civil Court a suit...
3,Purshottam_And_Anr_vs_State_Of_Madhya_Pradesh_...,1980,"R.S. Sarkaria, J. 1. Sixteen persons of villa..."
4,Thulia_Kali_vs_The_State_Of_Tamil_Nadu_on_25_F...,1972,This Court does not normally reappraise evide...

In [4]:
for i in range(10):

    print("="*100)

    print(sample_df.loc[i,"case_name"])

    print()

    print(
        sample_df.loc[i,"legal_summary"][:1500]
    )

    print("\n")

====================================================================================================
Rattan_Singh_Ran_Singh_And_Anr_vs_State_Of_Punjab_on_22_March_1988_1

 dated 19th March, 1984. These three appellants along with some others were prosecuted for offence under Section 302, 148 read with Section 149. It appears that there was some dispute about the land and the complainant party who were in possession of the agricultural land were sowing field at that moment. The accused persons(were) armed with various instruments of offence like barchi, ballam, lathies and dang. The complainant party attempted to run, but it is alleged that deceased Gaje Singh was hurt and assaulted by a number of persons as a result of which, he received as many as 13 injuries and ultimately resulting in his death. After trial these three appellants along with some others were convicted and sentenced for various offences as per details given below: Malkiat Singh Under Section 148 I.P.C RI for one year Under Section 302/149 I.P.C. Imprisonment for life. Under Section 325 I.P.C. RI for two years. Under Section 324/149 I.P.C. RI for one year. Under Section 324/149 I.P.C. RI for one year. Ran Singh, Dan Singh Under Section 148 I.P.C. RI for one year each. and Rattan Singh Under Section 302/149 I.P.C. Imprisonment for life each. Under Section 325/149 I.P.C. RI for two years. Under Section 324 I.P.C. RI for one year. 2. On appeal learned Judges of the High Court after considering the evidence acquitted all others, but convicted the present three appellants Ran Singh, Dan Singh and Rattan Singh and that all the three appellants have been convicted under Section 302 a


====================================================================================================
Punjab_National_Bank_vs_R_L_Vaid_And_Ors_on_20_August_2004_1

: 20/08/2004 BENCH: ARIJIT PASAYAT & C.K. THAKKER JUDGMENT: JUDGMENT 2004 Supp(3) SCR 692 The Judgment of the Court was delivered by ARIJIT PASAYAT, J. : Leave granted. Respondent Nos. l to 3 are facing trial for alleged commission of offences punishable under Section 120-B of the Indian Penal Code, 1860 (in short 'the I.P.C.'). read with Section 5(l)(d) of the Prevention of Corruption Act, 1947 ( in short 'the Act'). The case was registered by the Central Bureau of Investigation (in short 'the CBI'), which is respondent No. 4 in the present appeal. An application was filed by the accused persons before the Special Judge conducting trial for summoning eight documents, as were indicated in the application. The learned Special Judge directed production thereof overruling the objection to the production thereof. It was the stand of the CBI and the appellant-Bank that the documents were privileged communication in terms of Punjab National Bank vs R.L. Vaid And Ors on 20 August, 2004 / 1 Section 124 of the Indian Evidence Act, 1972 (in short 'the Act'). Originally, CBI had resisted the prayer and subsequently the appellant-Bank raised similar objection. The Special Judge was of the view that the production of the letters would not cause any injury to public interest and it would rather facilitate the court to arrive at an appropriate decision. It was noted that in such type of action proceedings, the court cannot be kept in dark, and in the administration of justice, the court sho


====================================================================================================
Magiti_Sasamal_vs_Pandab_Bissoi_on_20_September_1961_1

 The appellant filed in the Civil Court a suit for permanent injunction restraining the respondents from entering the lands in suit on the allegation that the lands belonged to him and were in his cultivatory possession for many years and that the respondents had no right or title to them and had never cultivated them. The respondents contended that they were tenants of portions of the said lands and were in Magiti Sasamal vs Pandab Bissoi on 20 September, 1961 / 1 cultivating possession of the same as tenants. The question which arose for decision was whether having regard to the provisions of S. 7(1) of the Orissa Tenants Protection Act, 1948, the Civil Court had jurisdiction to entertain the suit which involved a dispute as to the relationship of landlord and tenant between the parties. Held, that even on a liberal construction of s. 7(1) of the Act it cannot be held that disputes as regards the existence of the relationship of landlord and tenant fall to be deter- mined by the Collector under that section. Disputes which are entrusted to the Collector under s. 7(1) are the simple disputes specified therein in the five categories and do not include a serious dispute as to the relationship between the parties as landlord and tenant. In the present case the suit was therefore within the jurisdiction of the Civil Court. Secretary of State v. Mask & Co. (1940) L.R. 67 I.A. 222, referred to.


====================================================================================================
Purshottam_And_Anr_vs_State_Of_Madhya_Pradesh_on_3_October_1980_1

 R.S. Sarkaria, J. 1. Sixteen persons of village Tolkyakhedi were put on trial for the murder of one Kanahiya. The Sessions Judge convicted all of sixteen under Section 302/149, Indian Penal Code and sentenced each of them to imprisonment for life. On appeal, the High Court acquitted thirteen of them but maintained the conviction of Purshottam, Badrilal and Bansilal. Purshottam and Badrilal who are brothers, are now the appellants before us by special leave under Article 136 of the Constitution. 2. In village Tolkyakhedi, there are two warring factions, one led by Shivlal (P.W. 3) and the other by Purshottam appellant. There has been criminal litigation between these factions. The police had also initiated security proceeding against the two parties. 3. On September 6, 1972, about 9 or 10 months before the murder in question, Radhye Shyam son of Badrilal appellant was murdered, and Kanahiya deceased, Shri Krishan (P.W. 1) son of Shivlal (P.W. 3) along with others were being prosecuted for that murder. The deceased and his co-accused P.W. 1 had been released on bail. 4. The prosecution story as narrated at the trial was that on June 27. 1973 at about 4 p. m., deceased Kanahiva accompanied by Shri Krishan (P.W. 1) and Poona (P.W. 2) was returning from the fields. When he reached near the habitation of the village, the 16 accused persons variously armed confronted them. The appellants and Bansilal and three other accused were armed with Pharsis, Ramkaran was carrying a gun. whil


====================================================================================================
Thulia_Kali_vs_The_State_Of_Tamil_Nadu_on_25_February_1972_1

 This Court does not normally reappraise evidence in an appeal under article 136 of the Constitution but that fact would not prevent interference with an order of conviction, if, on consideration of the vital prosecution evidence in the case the Court finds it to be afflicted with ex-facie infirmity. The appellant was sentenced to death under s. 302 Indian Penal Code. The trial Court and the High Court based the Thulia Kali vs The State Of Tamil Nadu on 25 February, 1972 / 1 conviction of the appellant primarily upon the testimony of two witnesses one of whom according to the prosecution case was present when the accused made murderous assault on the deceased and the other arrived soon after. Neither of them nor anyone else who was told about the occurrence by the two witnesses made any report at the police station for more than 20 hours after the occurrence even though the police station was only two miles from the place of occurrence. Setting aside the conviction, HELD : That the delay in lodging the report would raise considerable doubt regarding the varacity of the evidence of two witnesses and point to an infirmity in that evidence and would render it unsafe to base the conviction of the apPellant. The first information report in a criminal case is an extremely vital and valuable piece of evidence for the purpose of corroborating the oral evidence adduced a' the trial The object of insisting upon prompt lodging of the report to the police in respect of commission of an o


====================================================================================================
Bhagloo_Lodh_Anr_vs_State_Of_U_P_on_14_June_2011_1

 and order dated 28.4.2004 passed by the High Court of Judicature at Allahabad (Lucknow Bench) in Criminal Appeal No. 956 of 2002 dismissing the appeal against the judgment and order dated 12.7.2002 passed by the Sessions Court, Hardoi, in Sessions Trial No. 108 of 2000 convicting the appellants and co-accused Bhagaloo Singh, under Sections 302/34 of Indian Penal Code, 1860 (hereinafter called as `IPC') and sentencing them to undergo rigorous imprisonment for life. 2. Facts and circumstances giving rise to this case are that: A) An FIR dated 26.10.1999 was lodged by Rajesh Singh (PW.1) in Police Station-Tandiyanwan, Fatehpur District, Hardoi, against the appellants and two other co-accused Ram Lakhan and Bhagaloo Singh that the said four accused had killed Vinod Kumar on 25.10.1999 at 9.00 P.M. Vinod Kumar, aged 22 years was friend of Raj Kumar, the son of Ram Lakhan, accused, and thus had visiting terms with the family. One day, when he went to the house of Ram Lakhan, accused, he saw Bhagaloo Singh, accused in compromising position with the daughter of Ram Lakhan, accused and reprimanded him. Bhagaloo Singh was living with Ram Lakhan, accused and helping him in his agricultural work. Bhagaloo Singh had told Vinod Kumar not to disclose the factum of his intimacy with the daughter of Ram Lakhan to anyone. Thus, a quarrel took place between the two and Bhagaloo Singh, accused threatened Vinod Kumar to face the dire consequences. It is in that consequence that the two appellant


====================================================================================================
Jamboo_Bhandari_vs_M_P_State_Industrial_Development_on_4_September_2023_1

 ABHAY S. OKA, J. Leave granted. 2. Heard learned counsel appearing for the parties. 3. The appellants in these two appeals were the accused before the learned Judicial Magistrate who tried them on a complaint filed by the respondent No. 1 under Section 138 of the Negotiable Instruments Act, 1881 (for short “N.I. Act”). The learned Magistrate convicted the appellants and directed them to pay the cheque amount of Rs. 2,52,36,985/- with interest thereon @ 9% per annum. An appeal was preferred by the appellants before the Sessions Court. Relying upon Section 148 of the N.I. Act, the Sessions Court granted relief under Section 389 of the Code of Criminal Procedure, 1973 (for short “Cr.P.C.”) subject to condition of appellants depositing 20% of the Jamboo Bhandari vs M.P. State Industrial Development ... on 4 September, 2023 / 1 amount of compensation. Vide the impugned judgment, the High Court has confirmed the order of the Sessions Court. 4. The High Court relied upon the decision of this Court in the case of Surinder Singh Deswal Alias Colonel S.S. Deswal and Others v. Virender Gandhi1. The High Court proceeded on the footing that, as this Court has interpreted the word “may” appearing in Section 148 as “shall”, the relief of suspension of sentence under Section 389 of the Cr.P.C. can be granted only by directing the accused to deposit minimum of 20% of the compensation/fine amount. 5. The paragraph ‘8’ of the decision of this Court in the case of Surinder Singh Deswal Alias Co


====================================================================================================
Nirmal_Chandra_Bhattacharjee_And_Ors_vs_Union_Of_India_Uoi_And_Ors_on_19_September_1990_1

 R.M. Sahai, J. 1. This appeal by grant of special leave is directed against order of Central Administrative Tribunal, Guwahati Branch. The question that arises for consideration is more of equity and fairplay than law. Therefore we proceed to exercise our jurisdiction under Article 136 read with Article 142, of the Constitution to do justice between the parties. 2. Both appellants and respondents 5 to 9 were working in class 'D' of N.F. Railways in pay scale of Rs. 200-240. Next class above it according to Railway Board circular dated 31st May, 1976 was 'C', with posts carrying scale of pay with a maximum of Rs. 290 but less than Rs. 900. 33 1/2% of posts in this class were to be filled by promotion from class 'D'. One of such posts was the post of Ticket Collector. It was a class 'III' post as compared to post held by appellants and respondents which were class 'IV posts. Selection by promotion for various categories was held in 1982. Since promotion to the post of Ticket Collector had not been held it was processed in pursuance of notice dated 22nd May 1983 in respect of existing vacancies. Written test was held in October 1983 and viva voce in February 1984 and those successful were appointed. Appellants are successful candidates. Respondents are those who despite having appeared could not get through. They therefore challenged selection in which they failed by taking resort to restructuring order issued by Railways on 1st August 1983. They claimed that since on 1st Augus


====================================================================================================
Rohit_Kochhar_vs_Vipul_Infrastructure_Developers_Ltd_on_26_November_2024_1

 it was held by the Supreme Court that reading the plaint as a whole in this case, there cannot be much doubt that the suit is essentially in relation to the relief of partition and declaration in respect of the properties situate in Village Pataudi, Gurgaon, outside the jurisdiction of court at Delhi. In that view of the matter it was also held that the Delhi Court will have no jurisdiction to try and decide the aforesaid suit. It was also held in the said decision by following the decision of Harshad Chiman Lal Modi(supra) that the relief of Rohit Kochhar vs Vipul Infrastructure Developers Ltd on 26 November, 2024 / 5 partition, accounting and declaration of invalidity of the sale executed in respect of immovable propertied situated situate in village Pataudi, Gurgaon could not entirely be obtained by personal obedience to the decree by the defendants in the suit. It was further held that applying the test laid down therein, it is clear that the present suit could not be brought within the purview of the Section 16 of the Code or entertained relying on Section 20 of the Code on the basis that three out of the five defendants are residing within the jurisdiction of the court at Delhi. 23. In view of the above facts and circumstances, we are of the considered opinion that the Delhi court would not have the territorial jurisdiction to entertain and decide the aforesaid suits. Consequently, we hold that the decision rendered by the learned Single judge cannot be upheld. The sam


====================================================================================================
A_N_D_Silva_vs_Union_Of_India_Uoi_on_6_December_1961

 Shah, J. 1. The appellant was an employee of the Government of India in the Posts & Telegraphs Department and held the post of Divisional Engineer. Telegraphs at Agra in 1947. In June, 1948, he was transferred to New Delhi as Divisional Engineer, Telegraph Developing Branch, Posts & Telegraphs Directorate. On September 18, 1948, the appellant was suspended from service and a chargesheet containing the following two charges was delivered to him :- "(i) That he, with a view to secure illegal gratification for himself and/or for others, committed serious irregularities in the matter of allotment of Telephones in Agra during the period he was Divisional Engineer, Telegraphs, Agra, and (ii) That by being a party to commission of gross irregularities in the matter of allotment of telephones in Agra, he facilitated acceptance of illegal gratification by his subordinates." 2. An appendix setting out the allegations on the basis of which the charges had been framed was also enclosed, and the appellant was called upon to submit his defence to the charges to the Enquiry Officer named therein. The appellant was further asked to show cause why, in the event of charge (i) being proved, he should not be dismissed from Government Service and, in the event of charge (ii) being proved, he should not be permanently degraded to the rank of the Electrical Supervisor or awarded any other lesser penalty. The appendix consisted of three heads which are as follows :- "(1) Contrary to the order conta

In [5]:
import pandas as pd
import numpy as np

df = pd.read_parquet(
    "../data/processed/summaries_only.parquet"
)

print(df.shape)

(26688, 3)

In [6]:
def assign_category(text):

    text = str(text).lower()

    if any(word in text for word in [
        "article 14",
        "article 19",
        "article 21",
        "fundamental right",
        "constitution",
        "constitutional"
    ]):
        return "Constitutional"

    elif any(word in text for word in [
        "murder",
        "conviction",
        "criminal",
        "ipc",
        "offence",
        "accused",
        "bail"
    ]):
        return "Criminal"

    elif any(word in text for word in [
        "property",
        "land",
        "tenant",
        "landlord",
        "mortgage",
        "ownership"
    ]):
        return "Property"

    elif any(word in text for word in [
        "contract",
        "agreement",
        "specific performance",
        "broker",
        "agency",
        "commission"
    ]):
        return "Contract"

    elif any(word in text for word in [
        "tax",
        "income tax",
        "assessment",
        "revenue",
        "deduction"
    ]):
        return "Tax"

    elif any(word in text for word in [
        "service",
        "promotion",
        "government servant",
        "disciplinary",
        "department"
    ]):
        return "Service"

    elif any(word in text for word in [
        "industrial dispute",
        "workman",
        "labour",
        "employee",
        "trade union"
    ]):
        return "Labour"

    elif any(word in text for word in [
        "consumer",
        "deficiency",
        "consumer protection"
    ]):
        return "Consumer"

    else:
        return "Other"

In [7]:
df["category"] = df[
    "legal_summary"
].apply(assign_category)

df["category"].value_counts()

category
Criminal          6127
Property          4749
Other             4515
Constitutional    4317
Contract          3800
Service           1937
Tax                795
Labour             411
Consumer            37
Name: count, dtype: int64

In [8]:
print(
    df["category"]
      .value_counts()
)

category
Criminal          6127
Property          4749
Other             4515
Constitutional    4317
Contract          3800
Service           1937
Tax                795
Labour             411
Consumer            37
Name: count, dtype: int64

In [9]:
df.to_parquet(
    "../data/processed/case_classification_dataset.parquet",
    index=False
)

print("Saved")

Saved

In [10]:
other_cases = df[
    df["category"] == "Other"
]

print(
    other_cases.shape
)

for i in range(20):

    print("="*100)

    print(
        other_cases.iloc[i]["case_name"]
    )

    print()

    print(
        other_cases.iloc[i]["legal_summary"][:1200]
    )

    print()

(4515, 4)
====================================================================================================
Ashutosh_Lahiry_vs_The_State_Of_Delhi_And_Anr_on_19_May_1950_1

 "You came to Delhi on March 27, 1950 and held a press conference in which you gave a highly exaggerated and communal version of happenings in Bengal and East Bengal. It is understood that since after the press conference your activities have continued to be of a nature inciting communal passions. It has also come to notice that your activities during your stay in West Bengal had also been of a communal nature. Your activities in the present atmosphere in Delhi where a communal riot took place on March 19, 1950 as a result of the intemperate statements made in a public meeting, are likely to create hatred between different communities which may lead to disturbance of public peace and order." The petitioner alleges that his object in coming to Delhi was not to create any communal bitterness. He came here in March 1950 to attend a Board meeting. It is true that he held a Press conference but no report was published in any newspaper and, therefore, there can be no question of his comments having created any mischief even if they were highly communal, which is denied. On the 1st April, 1950 he came to attend the two meetings but the meetings were banned and no mischief can possibly be

====================================================================================================
Gnanambal_Ammal_vs_T_Raju_Ayyar_And_Others_on_21_October_1950_1

 The cardinal maxim to be observed by courts in constru- ing a will is to endeavour to ascertain the infentions of the testator. This intention has to be gathered primarily from the language of the document which is to be read as a whole without indulging in any conjecture or speculation as to what the testator would have done if he had been better informed or better advised. The courts are however entitled and bound to bear in mind other matters than merely the words used. They must consider the surrounding circumstances, the position of the Gnanambal Ammal vs T. Raju Ayyar And Others on 21 October, 1950 / 1 testator, his family relationship, the probability that he would use words in a particular sense, and many other things which are often summed up in the somewhat picturesque figure the court is entitled to put itself into the testator's armchair '. But all this is solely as an aid to arriving at a right construetion of the will, and to ascertain the meaning of the language when used by that particular testator in that document. As soon as the construction is settled, the duty of the court is to carry out the intsentions as expressed. The court is in no case justified in adding

====================================================================================================
In_The_Supreme_Court_Of_India_vs_Kadar_Unnisa_Begum_And_Others_on_12_October_1950_1

 A Muhammadan widow in possession of her husband's estate in lieu of her claim for dower with the consent of the other heirs or otherwise is not entitled to priority as against his other unsecured creditors. There is nothing inherent in the very nature of dower which entitles it to priority. 748 Ameer Ammal v. Sankaranarayana Chetty (I.L.R. 25 Mad 658), Meet Meher Ally v. Mst. Areanee (11 W.R. 212), Maina Bibi v. Wasi Ahmad (I.L.R 41 All. 558), Hamira Bibi v. Zubaida- [In The Supreme Court Of India ... vs Kadar Unnisa Begum And Others on 12 October, 1950 / 1 Bibi (A.I.R. 1916 P.C. 46), Imtiaz Begum v. Abdul Karim Khan (A.I.R. 1930 All. 881) referred Kulsum Bibi v. Shiam Sunder Lal (A.I.R. 1936 All. 600), Mst. Ghafooran v. Ram Chandra Das (A.I.R. 1934 All. 168), Mohamed Turabuddin v. Yasin Beeum (17 D.L.R. 224)disap- proved. Maina Bibi, v. Chaudhri Vakil Abroad (52 I.A. 145) ex- plained.

====================================================================================================
In_The_Supreme_Court_Of_India_vs_Nandlal_on_12_October_1950_1

 Section 42 of the Co-operative Credit Societies Act, 1340 (Hyderabad) provided as follows: "If an award given by the Registrar or by a person nominated by him, or by a committee of arbitrators is not acted upon, then the Regis- trar can have it enforced--(a) through a civil court on a certificate issued by him. The civil court will treat the award in the same way as its own decree;(b) through a Reve- nue Court or oficer by issuing a certificate to that court or officer." [In The Supreme Court Of India ... vs Nandlal on 12 October, 1950 / 1 Held, that under the section the Registrar was not in the same position as a court passing the decree under the Civil Procedure Code in the matter of execution of the decree and he does not possess all the powers of an executing court. Where a dispute arose between a member of a society and the society and an arbitrator appointed under the Act passed a decree for payment of a certain sum in six monthly instal- ments with a condition that if default was made in the payment of any instalment the whole amount will become due, and under the provisions of s. 42 the decree was sent for execution to the Civil Court on a certificate of Registrar: 95 742

====================================================================================================
In_The_Supreme_Court_Of_India_vs_Shankar_And_Others_on_13_October_1950_1

 A instituted a suit for possession of two-thirds share in an estate against B and C who claimed a one-third share each in it. The suit was decreed by the trial court. B and [In The Supreme Court Of India ... vs Shankar And Others on 13 October, 1950 / 1 C preferred (1) I.L.R. 25 Mad. 658, 755 separate appeals, These appeals were heard together and disposed of by the same

====================================================================================================
Janardan_Reddy_And_Others_vs_The_State_on_14_December_1950_1

 The petitioners, who were convicted and sentenced to death by a special tribunal in the Hyderabad State, preferred appeals to the High Court of Hyderabad which were dismissed, and the applied to the High Court on the 21st Jan., 1950, for leave to appeal to the Judicial Committee of Hyderabad against the

====================================================================================================
Mahasay_Ganesh_Prasad_Ray_And_Anr_vs_Narendra_Nath_Sen_And_Ors_on_1_December_1950_1

 Kania, C.J. 1. This is an appeal from the judgment and decree of the High Court of Judicature at Patna (Cuttack Circuit) reversing the decree of the Subordinate Judge and dismissing the suit of the plaintiffs. The relevant facts material for deciding the points urged before us in the appeal are these. Rai Bahadur Govind Ballab Ray died on 30-7-1896. By his first wife, who had predeceased him, he had a daughter Sabitri who died about two months after Govind Ballab's death. Govind Ballab left him surviving a widow Sarnamayee, who died in 1935, She gave birth to a son, Lal, who died in infancy, and a daughter, Indubala, who died in 1904. The deceased Govind Ballab Ray had left also certain debutter properties but no decision in respect of those properties was given as the proper contesting parties were not before the Court. It was contended on behalf of the plaintiffs (appellants before us) that they are the next reversioners of Govind Ballab on the death of Sarnamayee. On behalf of the defendants (respondents) it was contended that the first wife of Govind Ballab had given birth to a second daughter Binodini on 29th of Baisakhi 1287 (9-5-1880) and that Binodini died in 1938 after th

====================================================================================================
Nanalal_Zaver_And_Another_vs_Bombay_Life_Assurance_Co_Ltd_And_on_4_May_1950_1

 A company was incorporated with a capital divided into 10,000 shares. After 5,404 shares had been subscribed, the directors of the company, finding that a businessman who had several other businesses and who was likely to use the funds of this company for his own businesses, was trying to get control of this company by purchasing its shares, resolved to issue the remaining 4,596 shares and offered these shares to the existing shareholders in the proportion of four new shares for every five shares held by them. Two of the share- holders of the company instituted a suit against the company and the directors for the following reliefs: (i) a declara- tion that the resolution of the directors and the offer of shares contravened the provisions of section 105-C of the Indian Companies Act, 1913, and was therefore ultra vires and illegal; (ii) a declaration that the offer of shares was not made bona fide or in the interests of the company and was therefore illegal; and (iii) to restrain the defend- ants from allotting any shares in pursuance of their offer: Held per KANIA CI.J., MAHAJAN, MUKHERJEA and DAS JJ.- that inasmuch as the shares resolved to be issued were offered to the existing

====================================================================================================
State_Of_Bombay_vs_Narothamdas_Jethabai_And_Anr_on_20_December_1950_1

 Fazl Ali, J. 1. I have read the judgment prepared by my brother, Mahajan J., and generally agree with his conclusions and reasonings, but, having regard to the importance of the points raised, I wish to add a short judgment of my own. 2. There are really three questions to be decided in this appeal, and they are as follows : (1) Whether the Bombay City Civil Court Act, 1948 (Act XL of 1948), is ultra vires the Legislature of the State of Bombay; (2) Whether in any event Section 4 of the above Act is ultra vires the State Legislature; and (3) Whether the Bombay High Court has jurisdiction to try the suit. 3. The first and the third questions have been answered by the High Court in favour of the appellant, and the second question has been answered in favour of the respondents. In this Court, the appellant attacked the judgment of the High Court in so far as it concerns the second question, whereas the first respondent attacked it in so far as it concerns the first and the third questions. 4. The Bombay City Civil Court Act purports to create an additional civil court for Greater Bombay having jurisdiction to try, receive and dispose of all suits and other proceedings of a civil natu

====================================================================================================
The_State_Of_Tripura_vs_The_Province_Of_East_Bengalunion_Of_on_20_December_1950_1

 The Bombay City Civil Court Act of 1948, an Act passed by the Provincial Legislature of Bombay, provided by s. 3 that the Provincial Government may, by notification in the official Gazette, establish for the Greater Bombay a court to be called the Bombay City Civil Court, and that this court shall, notwithstanding anything contained in any law, have jurisdiction to receive, try' and dispose of all suits and other proceedings of a civil nature nob exceeding Rs. 10,000 in value arising within Greater Bombay except certain kinds of suits which were specified in the section. Section 4 of the Act provided that subject to the exceptions speci- fied in 8. 3 the Provincial Government may, by notification in the official Gazette, invest the City Civil Court with jurisdiction to 52 receive, try and dispose of all suits and other proceedings of civil nature arising within the Greater Bombay and of such value not exceeding Rs. 25,000 as may be specified in the notification. Section 12 barred the jurisdiction of the Bombay High Court to try suits and proceedings cognizable by the City Civil Court. In exercise of the powers conferred by s. 4 the Provincial Government invested the City Civil Cou

====================================================================================================
Yeswant_Deorao_Deshmukh_vs_Walchand_Ramchand_Kothari_on_1_December_1950_1

 An application for execution of a decree was made after the expiry of 12'years from the date of the decree and 3 years from the date of the final order on the last previous application for execution. The decree-holder contended that the

====================================================================================================
Arjan_Singh_Alias_Puran_vs_Kartar_Singh_And_Others_on_2_March_1951_1

 The discretion to receive and admit additional evidence in appeal is not an arbitrary one but is a judicial one circumscribed by the limitations specified in O. XLI, r. 27, Arjan Singh Alias Puran vs Kartar Singh And Others on 2 March, 1951 / 1 of the Civil Procedure Code, and if additional evidence was allowed to be adduced contrary to the principles governing the reception of such evidence, it would be a case of im- proper exercise of discretion, and the additional evidence so brought on the record will have to be ignored and the case decided as if it was non-existent. 259 The legitimate occasion for admitting additional evi- dence in appeal is when on examining the evidence as it stands some inherent lacuna or defect becomes apparent, not where a discovery is made outside the court, of fresh evi- dence, and an application is made to import it. The true test is whether the appellate court is able to pronounce

====================================================================================================
Chandrasingh_Manibhai_And_Others_vs_Surjit_Lal_Ladhamal_Chhabdaand_Others_on_23_February_1951_1

 The Bombay Rents, Hotel and Lodging House Rates Control Act, LVII of 1947, which came into force on the 13th Febru- ary, 1948, has no application to appeals which were pending at the time when the Act came into force. Its retrospective effect is limited to cases mentioned in s. 50 of the Act, Chandrasingh Manibhai And Others vs Surjit Lal Ladhamal Chhabdaand Others on 23 February, 1951 / 1 that is to say, to suits and proceedings which were trans- ferred under the provisions of the said section to the courts having jurisdiction under the Act. Section 12 of the said Act is in terms prospective and not retrospective in effect. Sub-section (2) relates to suits which may be instituted after the Act comes into force and sub-s. (3) also only applies to such suits. Nilkanth v. Rasiklal (A.I.R. 1949 Bom. 210) approved.

====================================================================================================
Harla_vs_The_State_Of_Rajasthan_on_24_September_1951_1

 Natural justice requires that before a law can become operative it must be promulgated or published. It must be broadcast in some recognisable way so that all men may know what it is; or at least there must be some special rule or regulation or customary channel by or through which such Harla vs The State Of Rajasthan on 24 September, 1951 / 1 knowledge can be acquired with the exercise of due and reasonable diligence. The Council of Ministers appointed by the Crown Repre- sentative for the government and administration of the Jaipur State passed a Resolution in 1923 purporting to enact a law called the Jaipur Opium Act, but this law was neither promulgated or published in the Gazette nor made known to the public. The Jaipur Laws Act, 1923, which was also passed by the Council and which came into force on the 1st November, 1924, provided by s. 3 (b) that the law to be administered by the court of the Jaipur State shall be..." (b) all the regulations now in force within the said terri- tories and the enactments and regulations that may hereafter be passed from time to. time by the State and published in the Official Gazette." In 1938 the Jaipur Opium Act was amended by adding a cla

====================================================================================================
Makhan_Singh_Tarsikka_vs_The_State_Of_Punjab_on_10_December_1951_1

 Makhan Singh Tarsikka vs The State Of Punjab on 10 December, 1951 / 1 Whatever might be the position under the Preventive Detention Act of 1950 before it was amended in 1951, under the Act as amended in 1951, the Government should determine what the period of detention should be only after the Advi- sory Board to which the case is referred reports that the detention is justified. Fixing of the period of detention in the initial order itself is contrary to the scheme of the Act and cannot be supported. It cannot be treated as a mere surplusage as it would tend to prejudice a fair considera- tion of the detenu's case by the Advisory Board, though he would have to be released forthwith if the Advisory Board reports that there is no sufficient cause for detention. Before a person is deprived of his personal liberty the procedure established by law must be strictly followed and must not be departed from to the disadvantage of the person affected.

====================================================================================================
Mummareddi_Nagi_Reddi_And_Others_vs_Pitti_Durairaja_Naidu_And_Others_on_8_May_1951_1

 Where a Hindu widow who had inherited her husband's estate executed a deed, described as a deed of release, in favour of her daughter who was the next reversioner and the daughter's husband jointly: Held, that though under the Hindu Law it is open to a widow to surrender the estate to the next reversioner even Mummareddi Nagi Reddi And Others vs Pitti Durairaja Naidu And Others on 8 May, 1951 / 1 though the latter is a female heir, a widow cannot validly surrender in favour of the next female heir and a stranger jointly. Such a transaction cannot be treated as a surren- der in favour of the female heir and a transfer by the latter to the stranger, and is not binding upon the ultimate reversioners. Jagrani v. Gaya (A.I.R. 1933 All. 8561 approved. Nobo Kishore v. Harinath (I.L.R. 10 Cal. 1102) commented upon. Vytla Sitanna v. Marivada (L R. 61 I.A. 200), Rangasa- mi Goundan v. Nachiappa Goundan (41 I.A. 72) and Debi Prosad v. Gola Bhagat (I.L.R. 40 Cal. 721) referred to. In a suit by the reversioner to set aside an alienation made by a Hindu widow mesne profits can be awarded to the reversioner from the date of the widow's death even though such an alienation is not void. Even in ca

====================================================================================================
Ramnandan_Prasad_Narayan_Singh_vs_Mahanth_Kapildeo_Ram_Jee_on_12_January_1951_1

 Where a fresh document is executed for the amount remaining due on account of principal and interest under a loan ad- vanced prior document, and a suit is brought for recovery of the amount due under the later document with interest due thereunder, "the amount of loan mentioned in, or evidenced Ramnandan Prasad Narayan Singh vs Mahanth Kapildeo Ram Jee ... on 12 January, 1951 / 1 by, such document" for the purposes of s. 7 of the Bihar Money-Lenders Regulations and Transactions) Act, 1939, is the amount mentioned, or evidenced by, the later document and not that mentioned in the original document which was renewed; and the court can pass a decree for an amount of interest for the period preceding the institution of the suit, which together with any amount realised as interest after the date of the later document, is not greater than the amount of loan mentioned in the later document. The maximum amount that can be so decreed is not the amount which together with the interest realised from the date of the original loan does not exceed the original loan. Singheswar Singh and Other's v. Nadni Prasad Singh and Others (A.I.R. 1940 Pat. 65), Lal Singh v. Ramnarain Ram and Others (,A.I.R

====================================================================================================
Sant_Lal_Mahton_vs_Kamala_Prasad_on_17_October_1951_1


In [11]:
other_cases = df[df["category"]=="Other"]

for i in range(100):
    print("="*80)
    print(other_cases.iloc[i]["case_name"])
    print()
    print(other_cases.iloc[i]["legal_summary"][:500])

================================================================================
Ashutosh_Lahiry_vs_The_State_Of_Delhi_And_Anr_on_19_May_1950_1

 "You came to Delhi on March 27, 1950 and held a press conference in which you gave a highly exaggerated and communal version of happenings in Bengal and East Bengal. It is understood that since after the press conference your activities have continued to be of a nature inciting communal passions. It has also come to notice that your activities during your stay in West Bengal had also been of a communal nature. Your activities in the present atmosphere in Delhi where a communal riot took place o
================================================================================
Gnanambal_Ammal_vs_T_Raju_Ayyar_And_Others_on_21_October_1950_1

 The cardinal maxim to be observed by courts in constru- ing a will is to endeavour to ascertain the infentions of the testator. This intention has to be gathered primarily from the language of the document which is to be read as a whole without indulging in any conjecture or speculation as to what the testator would have done if he had been better informed or better advised. The courts are however entitled and bound to bear in mind other matters than merely the words used. They must consider th
================================================================================
In_The_Supreme_Court_Of_India_vs_Kadar_Unnisa_Begum_And_Others_on_12_October_1950_1

 A Muhammadan widow in possession of her husband's estate in lieu of her claim for dower with the consent of the other heirs or otherwise is not entitled to priority as against his other unsecured creditors. There is nothing inherent in the very nature of dower which entitles it to priority. 748 Ameer Ammal v. Sankaranarayana Chetty (I.L.R. 25 Mad 658), Meet Meher Ally v. Mst. Areanee (11 W.R. 212), Maina Bibi v. Wasi Ahmad (I.L.R 41 All. 558), Hamira Bibi v. Zubaida- [In The Supreme Court Of In
================================================================================
In_The_Supreme_Court_Of_India_vs_Nandlal_on_12_October_1950_1

 Section 42 of the Co-operative Credit Societies Act, 1340 (Hyderabad) provided as follows: "If an award given by the Registrar or by a person nominated by him, or by a committee of arbitrators is not acted upon, then the Regis- trar can have it enforced--(a) through a civil court on a certificate issued by him. The civil court will treat the award in the same way as its own decree;(b) through a Reve- nue Court or oficer by issuing a certificate to that court or officer." [In The Supreme Court O
================================================================================
In_The_Supreme_Court_Of_India_vs_Shankar_And_Others_on_13_October_1950_1

 A instituted a suit for possession of two-thirds share in an estate against B and C who claimed a one-third share each in it. The suit was decreed by the trial court. B and [In The Supreme Court Of India ... vs Shankar And Others on 13 October, 1950 / 1 C preferred (1) I.L.R. 25 Mad. 658, 755 separate appeals, These appeals were heard together and disposed of by the same
================================================================================
Janardan_Reddy_And_Others_vs_The_State_on_14_December_1950_1

 The petitioners, who were convicted and sentenced to death by a special tribunal in the Hyderabad State, preferred appeals to the High Court of Hyderabad which were dismissed, and the applied to the High Court on the 21st Jan., 1950, for leave to appeal to the Judicial Committee of Hyderabad against the
================================================================================
Mahasay_Ganesh_Prasad_Ray_And_Anr_vs_Narendra_Nath_Sen_And_Ors_on_1_December_1950_1

 Kania, C.J. 1. This is an appeal from the judgment and decree of the High Court of Judicature at Patna (Cuttack Circuit) reversing the decree of the Subordinate Judge and dismissing the suit of the plaintiffs. The relevant facts material for deciding the points urged before us in the appeal are these. Rai Bahadur Govind Ballab Ray died on 30-7-1896. By his first wife, who had predeceased him, he had a daughter Sabitri who died about two months after Govind Ballab's death. Govind Ballab left him
================================================================================
Nanalal_Zaver_And_Another_vs_Bombay_Life_Assurance_Co_Ltd_And_on_4_May_1950_1

 A company was incorporated with a capital divided into 10,000 shares. After 5,404 shares had been subscribed, the directors of the company, finding that a businessman who had several other businesses and who was likely to use the funds of this company for his own businesses, was trying to get control of this company by purchasing its shares, resolved to issue the remaining 4,596 shares and offered these shares to the existing shareholders in the proportion of four new shares for every five shar
================================================================================
State_Of_Bombay_vs_Narothamdas_Jethabai_And_Anr_on_20_December_1950_1

 Fazl Ali, J. 1. I have read the judgment prepared by my brother, Mahajan J., and generally agree with his conclusions and reasonings, but, having regard to the importance of the points raised, I wish to add a short judgment of my own. 2. There are really three questions to be decided in this appeal, and they are as follows : (1) Whether the Bombay City Civil Court Act, 1948 (Act XL of 1948), is ultra vires the Legislature of the State of Bombay; (2) Whether in any event Section 4 of the above A
================================================================================
The_State_Of_Tripura_vs_The_Province_Of_East_Bengalunion_Of_on_20_December_1950_1

 The Bombay City Civil Court Act of 1948, an Act passed by the Provincial Legislature of Bombay, provided by s. 3 that the Provincial Government may, by notification in the official Gazette, establish for the Greater Bombay a court to be called the Bombay City Civil Court, and that this court shall, notwithstanding anything contained in any law, have jurisdiction to receive, try' and dispose of all suits and other proceedings of a civil nature nob exceeding Rs. 10,000 in value arising within Gre
================================================================================
Yeswant_Deorao_Deshmukh_vs_Walchand_Ramchand_Kothari_on_1_December_1950_1

 An application for execution of a decree was made after the expiry of 12'years from the date of the decree and 3 years from the date of the final order on the last previous application for execution. The decree-holder contended that the
================================================================================
Arjan_Singh_Alias_Puran_vs_Kartar_Singh_And_Others_on_2_March_1951_1

 The discretion to receive and admit additional evidence in appeal is not an arbitrary one but is a judicial one circumscribed by the limitations specified in O. XLI, r. 27, Arjan Singh Alias Puran vs Kartar Singh And Others on 2 March, 1951 / 1 of the Civil Procedure Code, and if additional evidence was allowed to be adduced contrary to the principles governing the reception of such evidence, it would be a case of im- proper exercise of discretion, and the additional evidence so brought on the
================================================================================
Chandrasingh_Manibhai_And_Others_vs_Surjit_Lal_Ladhamal_Chhabdaand_Others_on_23_February_1951_1

 The Bombay Rents, Hotel and Lodging House Rates Control Act, LVII of 1947, which came into force on the 13th Febru- ary, 1948, has no application to appeals which were pending at the time when the Act came into force. Its retrospective effect is limited to cases mentioned in s. 50 of the Act, Chandrasingh Manibhai And Others vs Surjit Lal Ladhamal Chhabdaand Others on 23 February, 1951 / 1 that is to say, to suits and proceedings which were trans- ferred under the provisions of the said section
================================================================================
Harla_vs_The_State_Of_Rajasthan_on_24_September_1951_1

 Natural justice requires that before a law can become operative it must be promulgated or published. It must be broadcast in some recognisable way so that all men may know what it is; or at least there must be some special rule or regulation or customary channel by or through which such Harla vs The State Of Rajasthan on 24 September, 1951 / 1 knowledge can be acquired with the exercise of due and reasonable diligence. The Council of Ministers appointed by the Crown Repre- sentative for the gov
================================================================================
Makhan_Singh_Tarsikka_vs_The_State_Of_Punjab_on_10_December_1951_1

 Makhan Singh Tarsikka vs The State Of Punjab on 10 December, 1951 / 1 Whatever might be the position under the Preventive Detention Act of 1950 before it was amended in 1951, under the Act as amended in 1951, the Government should determine what the period of detention should be only after the Advi- sory Board to which the case is referred reports that the detention is justified. Fixing of the period of detention in the initial order itself is contrary to the scheme of the Act and cannot be sup
================================================================================
Mummareddi_Nagi_Reddi_And_Others_vs_Pitti_Durairaja_Naidu_And_Others_on_8_May_1951_1

 Where a Hindu widow who had inherited her husband's estate executed a deed, described as a deed of release, in favour of her daughter who was the next reversioner and the daughter's husband jointly: Held, that though under the Hindu Law it is open to a widow to surrender the estate to the next reversioner even Mummareddi Nagi Reddi And Others vs Pitti Durairaja Naidu And Others on 8 May, 1951 / 1 though the latter is a female heir, a widow cannot validly surrender in favour of the next female h
================================================================================
Ramnandan_Prasad_Narayan_Singh_vs_Mahanth_Kapildeo_Ram_Jee_on_12_January_1951_1

 Where a fresh document is executed for the amount remaining due on account of principal and interest under a loan ad- vanced prior document, and a suit is brought for recovery of the amount due under the later document with interest due thereunder, "the amount of loan mentioned in, or evidenced Ramnandan Prasad Narayan Singh vs Mahanth Kapildeo Ram Jee ... on 12 January, 1951 / 1 by, such document" for the purposes of s. 7 of the Bihar Money-Lenders Regulations and Transactions) Act, 1939, is t
================================================================================
Sant_Lal_Mahton_vs_Kamala_Prasad_on_17_October_1951_1

 While s. 20 of the Limitation Act requires that the payment should be made before the expiration of the period of limitation, it does not require that the acknowledgement of the payment should also be made within that period. But it is essential that such acknowledgement, whether made before or after the period of limitation, must be in exist- ence prior to the institution of the suit. An acknowledge- ment of the payment by the defendant in a written statement Sant Lal Mahton vs Kamala Prasad o
================================================================================
Santosh_Kumar_Jain_vs_The_State_Union_Of_India_Intervener_on_5_March_1951_1

 Section 3 of the Essential Supplies (Temporary Powers) Act, 1946, provided as follows: (1) The Central Government, so far as it appears to it to be necessary or expedient for maintaining or increasing supplies of an essential commodity, or for securing their equitable distribution and availability at fair prices, may by notified order, provide for regulating or prohibiting the production, supply and distribution thereof, and trade and commerce therein. Without prejudice to the generality of the
================================================================================
Sree_Sree_Iswar_Gopal_Jieu_Thakur_vs_Pratapmal_Bagaria_And_Others_Civil_on_14_March_1951_1

 Where the issue is whether there was legal necessity for a particular transaction, if all the original parties to the transaction and those who could have given evidence on the relevant points have passed away, a recital consisting of the principal circumstances of the case assumes greater importance and cannot be lightly set aside. Sree Sree Iswar Gopal Jieu Thakur vs Pratapmal Bagaria And Others.(Civil ... on 14 March, 1951 / 1 Banga Chandra Dhar Biswas v. Jagat Kishore Chowdhuri (43 I.A. 249
================================================================================
Sukhdev_Singh_vs_Maharaja_Bahadur_Of_Gidhaur_on_2_May_1951_1

 Though there are several instances in which Government ghatwalls were included in the zemindary of other persons, yet where no clear evidence is forthcoming as to the true character of a ghatwali, the fact that the tenure is includ- ed within a zemindary and is covered by the jama assessed upon it should turn the scale in favour of the party who alleges that it is a tenure which is dependent upon the zemindary. The mere fact that the ghatwali was shown to be under the Collector cannot alter the
================================================================================
Thakur_Rudreshwari_Prasad_Sinha_vs_Srimati_Rani_Probhabhati_And_Others_on_26_October_1951_1

 Taluk Kakwara was in its origin a Zemindari Ghatwali tenure and continued to be so, and was in fact treated as such ever since. Even if by virtue of Captain Browne's Sanad it became a Government Ghatwali tenure, then under the Sanad of Raja Kadir Ali or after the Permanent Settle- ment at any rate, it became a Zemindari Ghatwali and as such alienable with the consent of the Zemindar according to the custom of Kharakpur judicially recognised [Nature and incidents of Ghatwali tenures discussed].
================================================================================
Amjad_Khan_vs_The_State_on_20_March_1952_1

 A communal riot broke out in a town between some Sindhi refugees and the local Muslims. The trouble started in a locality where most of the shopkeepers were Sindhis. The goods in the Muslim shops there were scattered and some Muslims lost their lives. Alarm spread to another locality where the shops of appellant and his brother (both Muslims) were situated and the people there, including the appellant, started closing their shops. The family of the appellant's brother had taken shelter in the a
================================================================================
Boppanna_Venkateswaraloo_And_Others_vs_Superintendent_Central_on_24_November_1952_1

 The petitioner was served with an order of detention on the 20th October, 1951, and, after a reference to the Advisory Board, the Government confirmed the detention and specified Boppanna Venkateswaraloo And Others vs Superintendent, Central ... on 24 November, 1952 / 1 31st March, 1952, as the date up to which the detention was to continue, On the 20th March, 1952, the detention was extended till the 30th September, 1952, and on the 22nd September, 1952, the detention was again extended up to
================================================================================
Dattatreya_Moreshwar_Pangarkar_vs_The_State_Of_Bombay_And_Others_on_27_March_1952_1

 Section 11, sub-s. (1), of the Preventive Detention Act, 1950, provided that "in any case where the Advisory Board has reported that there is in its opinion sufficient cause for the detention of a person, the appropriate government may confirm the detention order and continue the detention for such period as it thinks fit". The case of the peti- tioner who was arrested under the Act was referred to the Advisory Board and on receiving a report from the Board that in its opinion there was suffici
================================================================================
Ebrahim_Aboobakar_And_Another_vs_Custodian_General_Ofevacuee_Property_on_26_May_1952_1

 A writ of certiorari cannot be granted to quash the decision of an inferior court within its jurisdiction on the ground that the decision is wrong. It must be shown before such a writ is issued that the authority which passed the order acted without jurisdiction or in excess of it, or in violation of the principles of natural justice. Want of jurisdiction may arise from the nature of the subject-mat- ter, so that the inferior court might not have authority to enter on the inquiry or upon some p
================================================================================
Ganpat_Rai_Hiralal_And_Another_vs_Aggarwal_Chamber_Of_Commerce_on_24_October_1952_1

 Section 116 of the Pepsu Ordinance X of 2005 (1948-1949) Ganpat Rai Hiralal And Another vs Aggarwal Chamber Of Commerce ... on 24 October, 1952 / 1 is a transitory regulation providing for a change over of proceedings 'from one set of courts in the covenanting State to others of like status in the Union, and for their continuance etc. in the latter courts. It does not mean that the proceedings must be treated as having freshly commenced. What is contemplated in the latter part of the section is
================================================================================
In_Re_The_Editor_Printer_Andpublisher_vs_Arabinda_Bose_And_Another_on_12_December_1952_1

 It is not the practice of the Supreme Court to issue a rule for contempt of Court except in very grave and serious cases and it is never over-sensitive to public criticism; but when there is danger of grave mischief being done in the matter of administration of justice, the animadversion will not be ignored and viewed with placid equanimity. In Re The Editor, Printer Andpublisher ... vs Arabinda Bose And Another on 12 December, 1952 / 1 A leading article in the " Times of India " on the
================================================================================
Keshardeo_Chamria_vs_Radha_Kissen_Chamria_And_Othersradha_on_30_October_1952_1

 A Subordinate Judge dismissed an application by a decree- holder for adjournment of an execution case and by the same order dismissed the execution case itself without informing the decree. holder's pleader that the application for adjournment had been dismissed and asking him whether be had to make any submission in 137 the matter of the execution case, and an application for restoration of the execution case setting aside the order of dismissal, the Subordinate Judge, finding that he had comm
================================================================================
Mahant_Pragdasji_Guru_Bhagwandasji_vs_Patel_Ishwarlalbhai_Narsibhai_on_7_March_1952_1

 In a suit under sec. 92 of the Civil Procedure Code alleging that the defendant had been guilty of misconduct Mahant Pragdasji Guru Bhagwandasji vs Patel Ishwarlalbhai Narsibhai ... on 7 March, 1952 / 1 and breach of trust as Mahant and praying, inter alia, that the temple and properties in suit be declared as a religious and charitable trust and the defendant be removed from the Gadi and a suitable successor appointed in his place, the District Judge and the High Court held concurrently that t
================================================================================
Musammat_Phool_Kuer_vs_Musammat_Pem_Kuer_And_Another_Pandit_on_24_April_1952_1

 A relinquishment by a Hindu widow of her estate in favour of the next reversioner and a stranger in equal moieties is not a valid surrender under Hindu law. A valid surrender cannot be made in favour of anybody except the next heir of the husband. Mummareddi Nagireddi v. Pitti Durairaja Naidu [1951] (S.C.R. 655) followed. Musammat Phool Kuer vs Musammat Pem Kuer And Another.Pandit ... on 24 April, 1952 / 1 It is competent to a Hindu widow to enter into a compro- mise in the course of the suit b
================================================================================
Nar_Hari_Sastri_And_Others_vs_Shri_Badrinath_Temple_Committee_on_9_May_1952_1
